addr = "root:123456@tcp(localhost:3306)/live_resource?timeout=2000ms&readTimeout=2000ms&writeTimeout=2000ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
[masterInfo]
    dBName = "ksync"
    user = "root"
    password = "root"
    charset = "utf8,utf8mb4"

[mysql]
    addr = "localhost:3306"
    dsn = "root:123456@tcp(localhost:3306)/live_resource?timeout=2000ms&readTimeout=2000ms&writeTimeout=2000ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    readDSN = ["root:123456@tcp(localhost:3306)/live_resource?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4","root:123456@tcp(localhost:3306)/live_resource?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"]
    active = 20
    idle = 10
    idleTimeout ="4h"
    queryTimeout = "1s"
    execTimeout = "1s"
    tranTimeout = "1s"

[db]
    [db.resource]
    dsn = "root:123456@tcp(localhost:3306)/live_resource?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
    active = 5
    idle = 1
    idleTimeout = "4h"

    # 从库
    [db.resourceReader]
     dsn = "root:123456@tcp(localhost:3306)/live_resource?timeout=200ms&readTimeout=200ms&writeTimeout=200ms&parseTime=true&loc=Local&charset=utf8,utf8mb4"
     active = 5
     idle = 1
     idleTimeout = "4h"

[canalInfo]
    [[canalInfo.instance]]
        addr = "localhost:3306"
        user = "root"
        password = "root"
        server_id = 1001
        [canalInfo.instance.masterInfo]
            addr = "localhost:3306"
            user = "root"
            password = "root"
            dbName = "canal"
        [[canalInfo.instance.sources]]
            schema = "test"
            tables = ["t_1","t_2"]
    [[canalInfo.instance]]
        addr = "localhost:3306"
        user = "root"
        password = "root"
        server_id = 1002
        [canalInfo.instance.masterInfo]
            addr = "localhost:3306"
            user = "root"
            password = "root"
            dbName = "canal"
        [[canalInfo.instance.sources]]
            schema = "test"
            tables = ["t_1","t_2"]
[log]
    dir = "/data/logs/ksync"
    Stdout = true